# Generated by Django 3.2.3 on 2021-06-01 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petshop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='url for picture of product')),
                ('description', models.CharField(max_length=200, verbose_name='description of product')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rating')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('brand', models.CharField(choices=[('Whiskas', 'Whiskas'), ('Natura Pet Products', 'Natura Pet Products'), ('Champion Petfoods', 'Champion Petfoods'), ('Golden Eagle HH', 'Golden Eagle HH'), ('Bosch Tiernahrung', 'Bosch Tiernahrung'), ("Hill's Pet Nutrition", "Hill's Pet Nutrition"), ('ROYAL CANIN', 'ROYAL CANIN'), ('Nestle Purina', 'Nestle Purina')], max_length=50, verbose_name='brand of the product')),
                ('animal', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Hamster', 'Hamster'), ('Other', 'Other')], max_length=50, verbose_name='animal species of the product')),
                ('classification', models.CharField(choices=[('Food', 'Food'), ('Nutrient', 'Nutrient'), ('Toy', 'Toy'), ('Accessories', 'Accessories')], max_length=50, verbose_name='type of product')),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('In other city', 'In other city'), ('Expected', 'Expected')], max_length=20, verbose_name='availability of product')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petshop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petshop.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petshop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petshop.product')),
            ],
        ),
    ]
