# Generated by Django 3.2.2 on 2021-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of product')),
                ('pic_url', models.CharField(max_length=200, verbose_name='url for picture of product')),
                ('description', models.CharField(max_length=200, verbose_name='description of product')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
