# Generated by Django 3.2.3 on 2021-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path3D',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='path dor 3D'),
        ),
    ]
