# Generated by Django 3.2.2 on 2021-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
