# Generated by Django 3.2.3 on 2021-06-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_auto_20210609_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Hamster', 'Hamster'), ('Other', 'Other')], max_length=50, verbose_name='animal species of the product')),
            ],
            options={
                'verbose_name_plural': 'animals',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Whiskas', 'Whiskas'), ('Natura Pet Products', 'Natura Pet Products'), ('Champion Petfoods', 'Champion Petfoods'), ('Golden Eagle HH', 'Golden Eagle HH'), ('Bosch Tiernahrung', 'Bosch Tiernahrung'), ("Hill's Pet Nutrition", "Hill's Pet Nutrition"), ('ROYAL CANIN', 'ROYAL CANIN'), ('Nestle Purina', 'Nestle Purina')], max_length=50, verbose_name='brand of the product')),
            ],
            options={
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Food', 'Food'), ('Nutrient', 'Nutrient'), ('Toy', 'Toy'), ('Accessories', 'Accessories')], max_length=50, verbose_name='type of product')),
            ],
            options={
                'verbose_name_plural': 'classifications',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='novelty',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='petshop.animal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='petshop.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='petshop.classification'),
        ),
    ]
