# Generated by Django 3.2.3 on 2021-06-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_auto_20210609_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.animal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.classification'),
        ),
    ]
