# Generated by Django 3.2.3 on 2021-06-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0004_auto_20210609_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
