# Generated by Django 3.2.3 on 2021-06-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0004_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='customer',
        ),
    ]
