# Generated by Django 3.2.2 on 2021-05-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
    ]
