# Generated by Django 3.2.2 on 2021-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_auto_20210509_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_url',
            field=models.CharField(max_length=200, verbose_name='url for picture of product'),
        ),
    ]
